title: Jasmine Garland
#logo: /images/headshot_border-min.jpg
description: PhD Student working at the confluence of the eletrical power grid, climate change, and extreme weather through a compuational lense. 
#ORCID ID: G-0MHBYB69TE
theme: jekyll-theme-minimal
